# Generated by Django 5.2.17 on 2026-09-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_ticket_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='massage',
            new_name='message',
        ),
    ]
