# Generated by Django 5.2.17 on 2026-09-19 10:50

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_massage_ticket_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_data',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_data',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
